# General settings

# specify API key for Alpha Vantage
api_key: "Q0V9QQQHF656ZKDB"

# Commodities from Alpha Vantage
commodities:
  monthly_only:
    - COPPER
    - ALUMINUM
    - WHEAT
    - CORN
    - COTTON
    - COFFEE
    - SUGAR
    - ALL_COMMODITIES
